### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by PabloPicose** [pplux/px#13]
I cant compile with the .bat. I am using 2014 VS with C++14 support
`
'px_sched::ObjectPool<px_sched::Scheduler::Task>::D::state': is not a type name, static, or enumerator
`

**Comment by PabloPicose** [comment]
Same with 2017 & 2019 VS versions

**Comment by PabloPicose** [comment]
It continues, except if I disable PX_SCHED_CACHE_LINE_SIZE

Only with this should work...

`#define PX_SCHED_IMPLEMENTATION 1`

`#include <px_sched.h>`


![imagen](https://user-images.githubusercontent.com/40830013/62708695-3098f480-b9f4-11e9-9018-0e84aaf16aa1.png)
![imagen](https://user-images.githubusercontent.com/40830013/62708726-3f7fa700-b9f4-11e9-81e5-0e6c66ef00cb.png)

![imagen](https://user-images.githubusercontent.com/40830013/62708897-95ece580-b9f4-11e9-9111-45a1fceb2a89.png)

**Comment by pplux** [comment]
Ummm... Thanks for reporting it! I have to update a couple of things, will do also check for that.

**Comment by pplux** [comment]
Clossing issue, since I can not reproduce it anymore. Looks like sometimes VS updates can break things around, but right now works properly as far as I can see. Feel free to reopen if still doesn't work for you :)
