### ISSUE TITLE
px_render_gltf. Out of bounds error because of sampler

### ISSUE THREAD

**Issue by NukeBird** [pplux/px#15]
Test model: [test_model.zip](https://github.com/pplux/px/files/3293949/test_model.zip)

For myself I just hardcoded 
```cpp
	new_texture.info.magnification_filter = SamplerFiltering::Linear;
        new_texture.info.minification_filter  = SamplerFiltering::LinearMipmapLinear;
        new_texture.info.wrapping[0] = SamplerWrapping::Repeat;
        new_texture.info.wrapping[1] = SamplerWrapping::Repeat;
        new_texture.info.wrapping[2] = SamplerWrapping::Repeat;
```
...and everything works. I have an assumption that the model has no legal samplers

So problem line is
https://github.com/pplux/px/blob/76a703379e96916210f14a4eeac60ff1d89c7cce/px_render_gltf.h#L303

**Comment by NukeBird** [comment]
we can try to make extra check aka
```cpp
if(model.samplers.size() < sampler_idx)
{
/* use sampler settings */
}
else
{
/* use default settings */
}
```

**Comment by NukeBird** [comment]
yeah, I checked my code once more. sampler_idx is -1 for all textures

**Comment by NukeBird** [comment]
https://github.com/pplux/px/pull/16

**Comment by pplux** [comment]
Thanks for the Fix!
