### ISSUE TITLE
Entry point is not defined in the examples

### ISSUE THREAD

**Issue by TesterPointer** [pplux/px#3]
Entry point is not defined in the examples, how can I execute it? 
I added the default "main" entry, and then call to  sokol_main(int argc, char **argv) with the default parameters.
Is there a preprocesor or something to determine the entry in your API?
Thanks, I am waiting for a reasonable documentation to how to start or something

**Comment by pplux** [comment]
Hi, sokol_main is just the function sokol calls, the real entry point is buried inside sokol_app.h, since we include the implementation the main comes along with that.
