### ISSUE TITLE
Question: Get the texture buffer id

### ISSUE THREAD

**Issue by PabloPicose** [pplux/px#4]
Hi,
how can I get the texture ID from a framebuffer?
frame_buffer.color_texture().id has invalid value...
It´s to use in the Imgui image

**Comment by pplux** [comment]
If you use the imgui implementation &frame_buffer.color_texture() should be enough.

**Comment by PabloPicose** [comment]
Ok, but other libs needs this, is there a method to get this?
Like Aplication

**Comment by PabloPicose** [comment]
Any solution to this???

**Comment by pplux** [comment]
In an abstraction rendering layer there should be no need to manually get the internal ID, to what purpose you need that?

**Comment by PabloPicose** [comment]
Yes, use a modified imgui lib for testing purpose, if its possible
